modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "villager_trading_plus"
version = "${version}"
displayName = "Villager Trading Plus"
authors = "cassiancc"
description = '''
Trade with Villagers faster - a port of Easier Villager Trading to Architectury.
'''
logoFile = "assets/villagertradingplus/icon.png"
issueTrackerURL = "https://github.com/cassiancc/Villager-Trading-Plus/issues"
displayURL="https://modrinth.com/mod/trading+"
modURL="https://modrinth.com/mod/trading+"


[[dependencies.villager_trading_plus]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.villager_trading_plus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "CLIENT"
