modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "villagertrading"
version = "${version}"
displayName = "Villager Trading Plus"
authors = "cassiancc"
description = '''
Trade with Villagers faster - a port of Easier Villager Trading to Architectury.
'''
logoFile = "assets/trading/icon.png"
issueTrackerURL = "https://github.com/cassiancc/Villager-Trading-Plus/issues"
displayURL="https://modrinth.com/mod/trading+"
modURL="https://modrinth.com/mod/trading+"

[[dependencies.villagertrading]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.villagertrading]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.villagertrading]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "villagertrading.mixins.json"
